import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Providers from '@/components/ui/Providers'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Quizmefy',
  description: 'Generated by create Saul Augusto Gasca Farrera - sgfarreradev@gmail.com',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className,'antialised min-h-screen pt-16')}>
       
       <Providers>

          <Navbar />
          {children}

          <Toaster />

       </Providers>
          
        
        
        </body>
    </html>
  )
}
